--drop it like it's hot
DROP TABLE moons;
DROP TABLE planets;
DROP TABLE users;
DROP TABLE galaxies;

-- user table
CREATE TABLE users (
    id SERIAL4 PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(300) NOT NULL,
    password_digest VARCHAR(400) NOT NULL,
    photo_url VARCHAR(400)
);

-- galaxy table
CREATE TABLE galaxies (
    id SERIAL4 PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    featured BOOLEAN,
    photo_url VARCHAR(400),
    blurb TEXT
);

-- planet table
CREATE TABLE planets (
    id SERIAL4 PRIMARY KEY,
    name TEXT NOT NULL,
    photo_url VARCHAR(400),
    galaxy_id INTEGER NOT NULL,
    featured BOOLEAN,
    blurb TEXT,
    FOREIGN KEY (galaxy_id) REFERENCES galaxies(id) ON DELETE RESTRICT
);

-- moons table

CREATE TABLE moons (
    id SERIAL4 PRIMARY KEY,
    name TEXT NOT NULL,
    photo_url VARCHAR(400),
    planet_id INTEGER NOT NULL,
    featured BOOLEAN,
    blurb TEXT,
    FOREIGN KEY (planet_id) REFERENCES planets(id) ON DELETE RESTRICT
);

INSERT INTO galaxies (featured,name, photo_url,blurb) values
(true,'Milky Way', 'https://i.ytimg.com/vi/G5AdrupH788/hqdefault.jpg','The Milky Way is the galaxy that contains our Solar System. The descriptive "milky" is derived from the appearance from Earth of the galaxy – a band of light seen in the night sky formed from stars that cannot be individually distinguished by the naked eye. -Wikipedia'),
(true,'Andromeda Galaxy', 'https://lh3.googleusercontent.com/qkNIVtQLbQuhOCmaJnwVJuRkAKAuaqxC6Zv-yi7ENPWovSGYnXog5fPyFpFfjo-gWd97VvIgiCqfG7Yby_JksPvkZY_lnoeSDxKNrIRjtEq2SdnGAVOqhrLJs1W16UwUmchhIxd0','The Andromeda Galaxy, also known as Messier 31, M31, or NGC 224, is a spiral galaxy approximately 780 kiloparsecs (2.5 million light-years) from Earth, and the nearest major galaxy to the Milky Way. Its name stems from the area of the sky in which it appears, the constellation of Andromeda. -Wikipedia'),
(false,'Triangulum Galaxy', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/M33_-_Triangulum_Galaxy.jpg
','The Triangulum Galaxy is a spiral galaxy approximately 3 million light-years (ly) from Earth in the constellation Triangulum. It is catalogued as Messier 33 or NGC 598. The Triangulum Galaxy is the third-largest member of the Local Group of galaxies, behind the Milky Way and the Andromeda Galaxy. It is one of the most distant permanent objects that can be viewed with the naked eye. The galaxy is the smallest spiral galaxy in the Local Group and it is believed to be a satellite of the Andromeda Galaxy due to their interactions, velocities, and proximity to one another in the night sky. It also has an H-II nucleus -Wikipedia'),
(true,'Centaurus A', 'https://upload.wikimedia.org/wikipedia/commons/e/ea/M33_-_Triangulum_Galaxy.jpg
','Centaurus A or NGC 5128 is a galaxy in the constellation of Centaurus. It was discovered in 1826 by Scottish astronomer James Dunlop from his home in Parramatta, in New South Wales, Australia. There is considerable debate in the literature regarding the galaxy''s fundamental properties such as its Hubble type (lenticular galaxy or a giant elliptical galaxy) and distance (10–16 million light-years). NGC 5128 is one of the closest radio galaxies to Earth, so its active galactic nucleus has been extensively studied by professional astronomers. The galaxy is also the fifth-brightest in the sky, making it an ideal amateur astronomy target,although the galaxy is only visible from low northern latitudes and the southern hemisphere. The center of the galaxy contains a supermassive black hole with a mass equivalent to 55 million solar masses, which ejects a relativistic jet that is responsible for emissions in the X-ray and radio wavelengths. By taking radio observations of the jet separated by a decade, astronomers have determined that the inner parts of the jet are moving at about half of the speed of light. X-rays are produced farther out as the jet collides with surrounding gases resulting in the creation of highly energetic particles. The X-ray jets of Centaurus A are thousands of light-years long, while the radio jets are over a million light-years long. -Wikipedia'),
(false,'Bode''s Galaxy', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/M81.jpg/1920px-M81.jpg','Messier 81 (also known as NGC 3031 or Bode''s Galaxy) is a spiral galaxy about 12 million light-years away, in the constellation Ursa Major. Due to its proximity to Earth, large size, and active galactic nucleus (which harbors a 70 million M☉ supermassive black hole), Messier 81 has been studied extensively by professional astronomers. The galaxy''s large size and relatively high brightness also make it a popular target for amateur astronomers. -Wikipedia'),
(false,'Southern Pinwheel Galaxy', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/M83_-_Southern_Pinwheel.jpg/1199px-M83_-_Southern_Pinwheel.jpg','Messier 83 (also known as the Southern Pinwheel Galaxy, M83 or NGC 5236) is a barred spiral galaxy approximately 15 million light-years away in the constellation Hydra. It is one of the closest and brightest barred spiral galaxies in the sky, making it visible with binoculars. Six supernovae (SN 1923A, SN 1945B, SN 1950B, SN 1957D, SN 1968L and SN 1983N) have been observed in M83. Its nickname of the Southern Pinwheel derives from its resemblance to the Pinwheel Galaxy. -Wikipedia'),
(false,'The Whirlpool Galaxy', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Messier51_sRGB.jpg/2560px-Messier51_sRGB.jpg','The Whirlpool Galaxy, also known as Messier 51a, M51a, and NGC 5194, is an interacting grand-design spiral galaxy with a Seyfert 2 active galactic nucleus. It lies in the constellation Canes Venatici, and was the first galaxy to be classified as a spiral galaxy. Its distance is estimated to be between 15 and 35 million light-years. The galaxy and its companion, NGC 5195, are easily observed by amateur astronomers, and the two galaxies may be seen with binoculars. The Whirlpool Galaxy has been extensively observed by professional astronomers, who study it to understand galaxy structure (particularly structure associated with the spiral arms) and galaxy interactions. -Wikipedia'),
(true,'The Tadpole Galaxy', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Tadpole_Galaxy_%28Arp_188%29.jpg','The Tadpole Galaxy is a disrupted barred spiral galaxy located 420 million light-years from Earth in the northern constellation Draco. Its most dramatic feature is a massive trail of stars about 280,000 light-years long; the size of the galaxy has been attributed to a merger with a smaller galaxy that is believed to have occurred about 100 million years ago. The galaxy is filled with bright blue star clusters.
It is hypothesized that a more compact intruder galaxy crossed in front of the Tadpole Galaxy—from left to right from the perspective of Earth—and was slung around behind the Tadpole by their mutual gravitational attraction. During this close encounter, tidal forces drew out the spiral galaxy''s stars, gas, and dust, forming the conspicuous tail. The intruder galaxy itself, estimated to lie about 300 thousand light-years behind the Tadpole, can be seen through foreground spiral arms at the upper left. Following its terrestrial namesake, the Tadpole Galaxy will likely lose its tail as it grows older, the tail''s star clusters forming smaller satellites of the large spiral galaxy. -Wikipedia'),
(false,'The Sunflower Galaxy', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Messier_63_GALEX_WikiSky.jpg','Messier 63 (also known as M63, NGC 5055, or the Sunflower Galaxy) is a spiral galaxy in the constellation Canes Venatici consisting of a central disc surrounded by many short spiral arm segments, the galaxy form known as flocculent. M63 is part of the M51 Group, a group of galaxies that also includes M51 (the ''Whirlpool Galaxy''). M63 is an active galaxy with a LINER nucleus. The existence of a super massive black hole (SMBH) at the nucleus is uncertain; if it does exist, then the mass is estimated as (8.5±1.9)×108 M☉. -Wikipedia');

INSERT INTO planets (featured,name, photo_url, galaxy_id, blurb) values
(true,'Earth', 'https://metrouk2.files.wordpress.com/2018/03/sei_3010712.jpg?w=748&h=392&crop=1',1,'Earth is the third planet from the Sun and the only astronomical object known to harbor life. According to radiometric dating and other sources of evidence, Earth formed over 4.5 billion years ago. Earth''s gravity interacts with other objects in space, especially the Sun and the Moon, Earth''s only natural satellite. Earth revolves around the Sun in 365.26 days, a period known as an Earth year. During this time, Earth rotates about its axis about 366.26 times. -Wikipedia'),
(true,'Saturn', 'https://solarsystem.nasa.gov/system/stellar_items/image_files/38_saturn_1600x900.jpg',1, 'Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius about nine times that of Earth. It has only one-eighth the average density of Earth, but with its larger volume Saturn is over 95 times more massive. Saturn is named after the Roman god of agriculture; its astronomical symbol (♄) represents the god''s sickle. -Wikipedia'),
(true,'Uranus', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Uranus2.jpg/1200px-Uranus2.jpg',1, 'Uranus is the seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System. Uranus is similar in composition to Neptune, and both have different bulk chemical composition from that of the larger gas giants Jupiter and Saturn. For this reason, scientists often classify Uranus and Neptune as "ice giants" to distinguish them from the gas giants. Uranus''s atmosphere is similar to Jupiter''s and Saturn''s in its primary composition of hydrogen and helium, but it contains more "ices" such as water, ammonia, and methane, along with traces of other hydrocarbons. It is the coldest planetary atmosphere in the Solar System, with a minimum temperature of 49 K (−224 °C; −371 °F), and has a complex, layered cloud structure with water thought to make up the lowest clouds and methane the uppermost layer of clouds. The interior of Uranus is mainly composed of ices and rock. -Wikipedia'),
(false,'Mercury', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Mercury_in_color_-_Prockter07-edit1.jpg/1920px-Mercury_in_color_-_Prockter07-edit1.jpg',1, 'Mercury is the smallest and innermost planet in the Solar System. Its orbital period around the Sun of 87.97 days is the shortest of all the planets in the Solar System. It is named after the Roman deity Mercury, the messenger of the gods.
Like Venus, Mercury orbits the Sun within Earth''s orbit as an inferior planet, and never exceeds 28° away from the Sun. When viewed from Earth, this proximity to the Sun means the planet can only be seen near the western or eastern horizon during the early evening or early morning. At this time it may appear as a bright star-like object, but is often far more difficult to observe than Venus. The planet telescopically displays the complete range of phases, similar to Venus and the Moon, as it moves in its inner orbit relative to Earth, which reoccurs over the so-called synodic period approximately every 116 days.
Mercury is tidally locked with the Sun in a 3:2 spin-orbit resonance, and rotates in a way that is unique in the Solar System. As seen relative to the fixed stars, it rotates on its axis exactly three times for every two revolutions it makes around the Sun. As seen from the Sun, in a frame of reference that rotates with the orbital motion, it appears to rotate only once every two Mercurian years. An observer on Mercury would therefore see only one day every two years. -Wikipedia'),
(false,'Venus', 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Venus-real_color.jpg',1, 'Venus is the second planet from the Sun, orbiting it every 224.7 Earth days. It has the longest rotation period (243 days) of any planet in the Solar System and rotates in the opposite direction to most other planets (meaning the Sun would rise in the west and set in the east). It does not have any natural satellites. It is named after the Roman goddess of love and beauty. It is the second-brightest natural object in the night sky after the Moon, reaching an apparent magnitude of −4.6 – bright enough to cast shadows at night and, rarely, visible to the naked eye in broad daylight.[14][15] Orbiting within Earth''s orbit, Venus is an inferior planet and never appears to venture far from the Sun; its maximum angular distance from the Sun (elongation) is 47.8°.
Venus is a terrestrial planet and is sometimes called Earth''s "sister planet" because of their similar size, mass, proximity to the Sun, and bulk composition. It is radically different from Earth in other respects. It has the densest atmosphere of the four terrestrial planets, consisting of more than 96% carbon dioxide. The atmospheric pressure at the planet''s surface is 92 times that of Earth, or roughly the pressure found 900 m (3,000 ft) underwater on Earth. Venus is by far the hottest planet in the Solar System, with a mean surface temperature of 735 K (462 °C; 863 °F), even though Mercury is closer to the Sun. Venus is shrouded by an opaque layer of highly reflective clouds of sulfuric acid, preventing its surface from being seen from space in visible light. -Wikipedia'),
(false,'Mars', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/OSIRIS_Mars_true_color.jpg/1920px-OSIRIS_Mars_true_color.jpg',1, 'Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System after Mercury. In English, Mars carries a name of the Roman god of war, and is often referred to as the "Red Planet" because the reddish iron oxide prevalent on its surface gives it a reddish appearance that is distinctive among the astronomical bodies visible to the naked eye. Mars is a terrestrial planet with a thin atmosphere, having surface features reminiscent both of the impact craters of the Moon and the valleys, deserts, and polar ice caps of Earth.
The rotational period and seasonal cycles of Mars are likewise similar to those of Earth, as is the tilt that produces the seasons. Mars is the site of Olympus Mons, the largest volcano and second-highest known mountain in the Solar System, and of Valles Marineris, one of the largest canyons in the Solar System. The smooth Borealis basin in the northern hemisphere covers 40% of the planet and may be a giant impact feature. Mars has two moons, Phobos and Deimos, which are small and irregularly shaped. These may be captured asteroids, similar to 5261 Eureka, a Mars trojan. -Wikipedia'),
(true,'Jupiter', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg',1, 'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a giant planet with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined. Jupiter and Saturn are gas giants; the other two giant planets, Uranus and Neptune, are ice giants. Jupiter has been known to astronomers since antiquity. The Romans named it after their god Jupiter. When viewed from Earth, Jupiter can reach an apparent magnitude of −2.94, bright enough for its reflected light to cast shadows,and making it on average the third-brightest natural object in the night sky after the Moon and Venus. Jupiter is primarily composed of hydrogen with a quarter of its mass being helium, though helium comprises only about a tenth of the number of molecules. It may also have a rocky core of heavier elements, but like the other giant planets, Jupiter lacks a well-defined solid surface. Because of its rapid rotation, the planet''s shape is that of an oblate spheroid (it has a slight but noticeable bulge around the equator). The outer atmosphere is visibly segregated into several bands at different latitudes, resulting in turbulence and storms along their interacting boundaries. A prominent result is the Great Red Spot, a giant storm that is known to have existed since at least the 17th century when it was first seen by telescope. Surrounding Jupiter is a faint planetary ring system and a powerful magnetosphere. Jupiter has at least 79 moons, including the four large Galilean moons discovered by Galileo Galilei in 1610. Ganymede, the largest of these, has a diameter greater than that of the planet Mercury. -Wikipedia');


INSERT INTO moons (featured,name, photo_url, planet_id, blurb) values
(false,'Earths'' Moon', 'http://jtgnew.sjrdesign.net/images/earth_moon_full.jpg',1,'The Moon is an astronomical body that orbits planet Earth and is Earth''s only permanent natural satellite. It is the fifth-largest natural satellite in the Solar System, and the largest among planetary satellites relative to the size of the planet that it orbits (its primary). The Moon is after Jupiter''s satellite Io the second-densest satellite in the Solar System among those whose densities are known. -Wikipedia'),
(true,'Pan', 'https://www.sciencespacerobots.com/2017pics/pan-saturn-moon-closeup.jpg',2,'Pan is the innermost moon of Saturn. It is a small, walnut-shaped moon approximately 35 kilometres across and 23 km wide that orbits within the Encke Gap in Saturn''s A Ring. Pan is a ring shepherd and is responsible for keeping the Encke Gap free of ring particles.
It was discovered by Mark R. Showalter in 1990 from analysis of old Voyager 2 probe photos and received the provisional designation S/1981 S 13 because the discovery images dated back to 1981. -Wikipedia'),
(false,'Daphnis', 'http://wwwcdn.skyandtelescope.com/wp-content/uploads/7576_PIA21055-768w.jpg',2,
'The Moon is an astronomical body that orbits planet Earth and is Earth''s only permanent natural satellite. It is the fifth-largest natural satellite in the Solar System, and the largest among planetary satellites relative to the size of the planet that it orbits (its primary). The Moon is after Jupiter''s satellite Io the second-densest satellite in the Solar System among those whose densities are known.
The Moon is thought to have formed about 4.51 billion years ago, not long after Earth. The most widely accepted explanation is that the Moon formed from the debris left over after a giant impact between Earth and a Mars-sized body called Theia. -Wikipedia'),
(false,'Atlas', 'https://www.newsmax.com/Newsmax/files/a8/a8a0763f-7f3b-4264-bdfd-cdaabaa94828.jpg',2,
'Atlas is an inner satellite of Saturn.
Atlas was discovered by Richard Terrile in 1980 (some time before November 12) from Voyager photos and was designated S/1980 S 28. In 1983 it was officially named after Atlas of Greek mythology, because it "holds the rings on its shoulders" like the Titan Atlas held the sky up above the Earth. It is also designated Saturn XV.
Atlas is the closest satellite to the sharp outer edge of the A ring, and was long thought to be a shepherd satellite for this ring. However, now it is known that the outer edge of the ring is instead maintained by a 7:6 orbital resonance with the larger but more distant moons Janus and Epimetheus. In 2004 a faint, thin ring, temporarily designated R/2004 S 1, was discovered in the Atlantean orbit. -Wikipedia'),
(false,'Phobos', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Phobos_colour_2008.jpg/450px-Phobos_colour_2008.jpg',6,
'Phobos (/ˈfoʊbəs/ FOH-bəs, /-bɒs/ -boss,[4] from Greek Φόβος; systematic designation: Mars I) is the innermost and larger of the two natural satellites of Mars, the other being Deimos. Both moons were discovered in 1877 by American astronomer Asaph Hall.
Phobos is a small, irregularly shaped object with a mean radius of 11 km (7 mi)[1] and is seven times as massive as the outer moon, Deimos. Phobos is named after the Greek god Phobos, a son of Ares (Mars) and Aphrodite (Venus) and the personification of horror (cf. phobia).
Phobos orbits 6,000 km (3,700 mi) from the Martian surface, closer to its primary body than any other known planetary moon. It is so close that it orbits Mars much faster than Mars rotates, and completes an orbit in just 7 hours and 39 minutes. As a result, from the surface of Mars it appears to rise in the west, move across the sky in 4 hours and 15 minutes or less, and set in the east, twice each Martian day.
Phobos is one of the least reflective bodies in the Solar System, with an albedo of just 0.071. Surface temperatures range from about −4 °C (25 °F) on the sunlit side to −112 °C (−170 °F) on the shadowed side. The defining surface feature is the large impact crater, Stickney, which takes up a substantial proportion of the moon''s surface. -Wikipedia'),
(true,'Deimos', 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Deimos-MRO.jpg',6,
'Deimos (systematic designation: Mars II) is the smaller and outer of the two natural satellites of the planet Mars, the other being Phobos. Deimos has a mean radius of 6.2 km (3.9 mi) and takes 30.3 hours to orbit Mars. In Greek mythology, Deimos is the twin brother of Phobos and personified terror.
Deimos is 23,460 km (14,580 mi) from Mars, much farther than Mars''s other moon, Phobos -Wikipedia'),
(true,'Atlas', 'https://www.newsmax.com/Newsmax/files/a8/a8a0763f-7f3b-4264-bdfd-cdaabaa94828.jpg',2,
'Atlas is an inner satellite of Saturn.
Atlas was discovered by Richard Terrile in 1980 (some time before November 12) from Voyager photos and was designated S/1980 S 28. In 1983 it was officially named after Atlas of Greek mythology, because it "holds the rings on its shoulders" like the Titan Atlas held the sky up above the Earth. It is also designated Saturn XV.
Atlas is the closest satellite to the sharp outer edge of the A ring, and was long thought to be a shepherd satellite for this ring. However, now it is known that the outer edge of the ring is instead maintained by a 7:6 orbital resonance with the larger but more distant moons Janus and Epimetheus. In 2004 a faint, thin ring, temporarily designated R/2004 S 1, was discovered in the Atlantean orbit. -Wikipedia'),
(false,'Miranda', 'https://upload.wikimedia.org/wikipedia/commons/e/e1/PIA18185_Miranda%27s_Icy_Face.jpg',3,
'Miranda, also designated Uranus V, is the smallest and innermost of Uranus''s five round satellites. It was discovered by Gerard Kuiper on 16 February 1948 at McDonald Observatory, and named after Miranda from William Shakespeare''s play The Tempest. Like the other large moons of Uranus, Miranda orbits close to its planet''s equatorial plane. Because Uranus orbits the Sun on its side, Miranda''s orbit is perpendicular to the ecliptic and shares Uranus''s extreme seasonal cycle.
At just 470 km in diameter, Miranda is one of the smallest closely observed objects in the Solar System that might be in hydrostatic equilibrium (spherical under its own gravity). The only close-up images of Miranda are from the Voyager 2 probe, which made observations of Miranda during its Uranus flyby in January 1986. During the flyby, Miranda''s southern hemisphere pointed towards the Sun, so only that part was studied. There are no active plans at present to return to study the moon in more detail, although various concepts such as a Uranus orbiter and probe have been proposed from time to time. -Wikipedia'),
(true,'Ariel', 'https://upload.wikimedia.org/wikipedia/commons/5/59/Ariel_%28moon%29.jpg',3,
'Ariel is the fourth-largest of the 27 known moons of Uranus. Ariel orbits and rotates in the equatorial plane of Uranus, which is almost perpendicular to the orbit of Uranus and so has an extreme seasonal cycle.
It was discovered in October 1851 by William Lassell and named for a character in two different pieces of literature. As of 2017, much of the detailed knowledge of Ariel derives from a single flyby of Uranus performed by the spacecraft Voyager 2 in 1986, which managed to image around 35% of the moon''s surface. There are no active plans at present to return to study the moon in more detail, although various concepts such as a Uranus orbiter and probe have been proposed from time to time.
After Miranda, Ariel is the second-smallest of Uranus'' five major rounded satellites and the second-closest to its planet. Among the smallest of the Solar System''s 19 known spherical moons (it ranks 14th among them in diameter), it is believed to be composed of roughly equal parts ice and rocky material. Its mass is approximately equal in magnitude to Earth''s hydrosphere. -Wikipedia'),
(false,'Umbriel', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/PIA00040_Umbrielx2.47.jpg',3,
'Umbriel is a moon of Uranus discovered on October 24, 1851, by William Lassell. It was discovered at the same time as Ariel and named after a character in Alexander Pope''s poem The Rape of the Lock. Umbriel consists mainly of ice with a substantial fraction of rock, and may be differentiated into a rocky core and an icy mantle. The surface is the darkest among Uranian moons, and appears to have been shaped primarily by impacts. However, the presence of canyons suggests early endogenic processes, and the moon may have undergone an early endogenically driven resurfacing event that obliterated its older surface.
Covered by numerous impact craters reaching 210 km (130 mi) in diameter, Umbriel is the second most heavily cratered satellite of Uranus after Oberon. The most prominent surface feature is a ring of bright material on the floor of Wunda crater. This moon, like all moons of Uranus, probably formed from an accretion disk that surrounded the planet just after its formation. The Uranian system has been studied up close only once, by the spacecraft Voyager 2 in January 1986. It took several images of Umbriel, which allowed mapping of about 40% of the moon’s surface. -Wikipedia'),
(true,'Titania', 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Titania_%28moon%29_color_cropped.jpg',3,
'Titania is the largest of the moons of Uranus and the eighth largest moon in the Solar System at a diameter of 1,578 kilometres (981 mi). Discovered by William Herschel in 1787, Titania is named after the queen of the fairies in Shakespeare''s A Midsummer Night''s Dream. Its orbit lies inside Uranus''s magnetosphere.
Titania consists of approximately equal amounts of ice and rock, and is probably differentiated into a rocky core and an icy mantle. A layer of liquid water may be present at the core–mantle boundary. The surface of Titania, which is relatively dark and slightly red in color, appears to have been shaped by both impacts and endogenic processes. It is covered with numerous impact craters reaching up to 326 kilometres (203 mi) in diameter, but is less heavily cratered than Oberon, outermost of the five large moons of Uranus. Titania probably underwent an early endogenic resurfacing event which obliterated its older, heavily cratered surface. -Wikipedia'),
(false,'Thebe', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Thebe.jpg',7,
'Thebe (/ˈθiːbiː/ THEE-bee; Greek: Θήβη) also known as Jupiter XIV, is the fourth of Jupiter''s moons by distance from the planet. It was discovered by Stephen P. Synnott in images from the Voyager 1 space probe taken on March 5, 1979, while making its flyby of Jupiter. In 1983, it was officially named after the mythological nymph Thebe.
The second largest of the inner satellites of Jupiter, Thebe orbits within the outer edge of the Thebe gossamer ring that is formed from dust ejected from its surface. It is irregularly shaped and reddish in colour, and is thought like Amalthea to consist of porous water ice with unknown amounts of other materials. Its surface features include large craters and high mountains—some of them are comparable to the size of the moon itself.
Thebe was photographed in 1979 by the Voyager 1 and 2 spacecraft, and later, in more detail, by the Galileo orbiter in the 1990s. -Wikipedia'),
(false,'Europa', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Europa-moon.jpg/450px-Europa-moon.jpg',7,
'Europa /jʊəˈroʊpə/ (About this sound listen) yoor-OH-pə[10] (Jupiter II) is the smallest of the four Galilean moons orbiting Jupiter, and the sixth-closest to the planet. It is also the sixth-largest moon in the Solar System. Europa was discovered in 1610 by Galileo Galilei and was named after Europa, the legendary mother of King Minos of Crete and lover of Zeus (the Greek equivalent of the Roman god Jupiter).
Slightly smaller than Earth''s Moon, Europa is primarily made of silicate rock and has a water-ice crust and probably an iron–nickel core. It has a tenuous atmosphere composed primarily of oxygen. Its surface is striated by cracks and streaks, whereas craters are relatively rare. In addition to Earth-bound telescope observations, Europa has been examined by a succession of space probe flybys, the first occurring in the early 1970s.
Europa has the smoothest surface of any known solid object in the Solar System. The apparent youth and smoothness of the surface have led to the hypothesis that a water ocean exists beneath it, which could conceivably harbor extraterrestrial life. The predominant model suggests that heat from tidal flexing causes the ocean to remain liquid and drives ice movement similar to plate tectonics, absorbing chemicals from the surface into the ocean below. Sea salt from a subsurface ocean may be coating some geological features on Europa, suggesting that the ocean is interacting with the seafloor. This may be important in determining if Europa could be habitable. In addition, the Hubble Space Telescope detected water vapor plumes similar to those observed on Saturn''s moon Enceladus, which are thought to be caused by erupting cryogeysers. In May 2018, astronomers provided supporting evidence of water plume activity on Europa, based on an updated critical analysis of data obtained from the Galileo space probe, which orbited Jupiter between 1995 to 2003. Such plume activity could help researchers in a search for life from the subsurface European ocean without having to land on the moon. -Wikipedia'),
(true,'Callisto', 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Callisto.jpg',7,
'Callisto /kəˈlɪstoʊ/ (Jupiter IV) is the second-largest moon of Jupiter, after Ganymede. It is the third-largest moon in the Solar System after Ganymede and Saturn''s largest moon Titan, and the largest object in the Solar System not to be properly differentiated. Callisto was discovered in 1610 by Galileo Galilei. At 4821 km in diameter, Callisto has about 99% the diameter of the planet Mercury but only about a third of its mass. It is the fourth Galilean moon of Jupiter by distance, with an orbital radius of about 1883000 km. It is not in an orbital resonance like the three other Galilean satellites—Io, Europa, and Ganymede—and is thus not appreciably tidally heated. Callisto''s rotation is tidally locked to its orbit around Jupiter, so that the same hemisphere always faces inward; Jupiter appears to stand nearly still in Callisto''s sky. It is less affected by Jupiter''s magnetosphere than the other inner satellites because of its more remote orbit, located just outside Jupiter''s main radiation belt.
Callisto is composed of approximately equal amounts of rock and ices, with a density of about 1.83 g/cm3, the lowest density and surface gravity of Jupiter''s major moons. Compounds detected spectroscopically on the surface include water ice, carbon dioxide, silicates, and organic compounds. Investigation by the Galileo spacecraft revealed that Callisto may have a small silicate core and possibly a subsurface ocean of liquid water at depths greater than 100 km. -Wikipedia')
